version = 1

[[annotations]]
path = [
    ".astro/*",
    ".editorconfig",
    ".github/**/*",
    ".gitignore",
    ".vscode/*",
    "CNAME",
    "REUSE.toml",
    "astro.config.mjs",
    "contrib/example-schema.json",
    "members.csv",
    "package-lock.json",
    "package.json",
    "public/images/example-members/*",
    "src/content/members/*",
    "src/env.d.ts",
    "tsconfig.json",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "src/assets/images/blobs/*",
    "public/favicon.svg",
    "public/favicon.png",
    "public/osspledge.pdf",
    "public/images/*",
    "public/logos/*",
]
SPDX-FileCopyrightText = "Â© 2024 Functional Software, Inc. d/b/a Sentry"
SPDX-License-Identifier = "LicenseRef-Restricted"

[[annotations]]
path = [
    "public/fonts/azaret-mono*",
]
SPDX-FileCopyrightText = "Copyright 2021 The Azeret Project Authors (https://github.com/displaay/azeret)"
SPDX-License-Identifier = "OFL-1.1"


[[annotations]]
path = [
    "public/fonts/libre-franklin*",
]
SPDX-FileCopyrightText = "Copyright (c) 2015, Impallari Type (www.impallari.com)"
SPDX-License-Identifier = "OFL-1.1"
